name: farmagrid
description: "FarmaGrid+ - Sua saúde digital integrada"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/medicamentos.png
    - assets/images/carol.jpeg
    - assets/images/aires.jpeg
    - assets/images/heloisa.jpeg
    
